# Generated by Django 3.0.5 on 2020-08-17 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('banner', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('stands_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeWebpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Expo')),
            ],
        ),
        migrations.CreateModel(
            name='VisitantRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Expo')),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='default', max_length=40, null=True)),
                ('logotipo', models.FileField(blank=True, null=True, upload_to='')),
                ('video_bienvenida', models.FileField(blank=True, null=True, upload_to='')),
                ('whatsapp', models.CharField(blank=True, max_length=80, null=True)),
                ('chat', models.CharField(blank=True, max_length=80, null=True)),
                ('webpage', models.CharField(blank=True, max_length=80, null=True)),
                ('flyer_file', models.FileField(blank=True, null=True, upload_to='')),
                ('exhibition_video', models.FileField(blank=True, null=True, upload_to='')),
                ('packageStand', models.CharField(choices=[('BAS', 'Basico'), ('PLS', 'Plus'), ('GOL', 'Gold'), ('PLA', 'Platinum'), ('DIA', 'Diamond')], default='BAS', max_length=3)),
                ('related_expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Expo')),
                ('visitantes', models.ManyToManyField(to='main.VisitantRegister')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=40, null=True)),
                ('user_type', models.CharField(choices=[('VIW', 'Visitante'), ('STO', 'Dueño de stand'), ('EXO', 'Dueño de expo'), ('STF', 'Staff'), ('ADM', 'Administrador')], default='VIW', max_length=3)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_expo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Expo')),
                ('user_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Stand')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('redirect_url', models.CharField(blank=True, max_length=100, null=True)),
                ('related_expo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Expo')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='default')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
