# Generated by Django 3.0.5 on 2020-08-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200825_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expodesign',
            options={'verbose_name': 'ExpoDesign', 'verbose_name_plural': 'ExpoDesigns'},
        ),
        migrations.AddField(
            model_name='expo',
            name='editKey',
            field=models.CharField(blank=True, default='default', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='editKey',
            field=models.CharField(blank=True, default='default', max_length=40, null=True),
        ),
    ]
