# Generated by Django 3.0.5 on 2020-08-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='user_expo',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='user_expo',
            field=models.ManyToManyField(blank=True, null=True, to='main.Expo'),
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='user_stand',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='user_stand',
            field=models.ManyToManyField(blank=True, null=True, to='main.Stand'),
        ),
    ]
