# Generated by Django 3.0.5 on 2020-08-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200830_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantregister',
            name='mail',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='visitantregister',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='visitantregister',
            name='tel',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
