# Generated by Django 3.0.5 on 2020-08-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200831_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='color1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='color2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stand',
            name='standType',
            field=models.IntegerField(default=0),
        ),
    ]
