# Generated by Django 3.0.5 on 2020-09-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200831_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='banner1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='banner2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
