# Generated by Django 3.0.5 on 2020-09-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200831_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
