# Generated by Django 3.0.5 on 2020-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200903_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='banner3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='banner4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='banner5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='banner6',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='banner_horizontal1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='banner_horizontal2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stand',
            name='banner_horizontal3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
