# Generated by Django 3.0.5 on 2020-09-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200914_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='senderIsSender',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.VisitantRegister'),
        ),
    ]
