# Generated by Django 3.0.5 on 2020-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200920_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
